services:
  minecraft:
    image: itzg/minecraft-server:${JAVA_VERSION:-latest}
    container_name: minecraft-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-25565}:25565"
    environment:
      MEMORY: "${MEMORY}"
      TZ: "${TZ}"
      TYPE: "${TYPE}"
      EULA: TRUE
      VERSION: "${VERSION}"
      MOTD: "${MOTD}"
      DIFFICULTY: "${DIFFICULTY}"
      MODE: "${MODE}"
      LEVEL: "${LEVEL}"
      ENABLE_WHITELIST: "${ENABLE_WHITELIST}"
      WHITELIST: "${WHITELIST}"
      MODRINTH_PROJECTS: "${MODRINTH_PROJECTS}"
      ONLINE_MODE: "${ONLINE_MODE}"
      MAX_PLAYERS: "${MAX_PLAYERS}"
      PVP: FALSE
    volumes:
      - ./minecraft-data:/data
    stdin_open: true
    tty: true
  backup:
    image: itzg/mc-backup
    restart: unless-stopped
    depends_on:
      minecraft:
        condition: service_healthy
    env_file:
      - .env
    environment:
      TZ: "${TZ}"
      BACKUP_INTERVAL: "30m"
      BACKUP_NAME: "${LEVEL}_backup"
    volumes:
      - ./minecraft-data:/data:ro