services:
  minecraft:
    image: itzg/minecraft-server:java21 # Check on Docker Hub for the java version required by the Minecraft version you want to run
    container_name: minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      MEMORY: 8G
      TZ: Brazil/Sao_Paulo
      TYPE: MODRINTH
      EULA: TRUE
      VERSION: 1.21.1 # Specify the Minecraft version you want to run
      MOTD: |
        Servidor §a§lVANILLA§r da rapaziada
        Versão §b§n%VERSION%§r
      DIFFICULTY: normal
      MODE: survival
      LEVEL: world
      ENABLE_WHITELIST: FALSE
      WHITELIST: ""
      ONLINE_MODE: TRUE
      MAX_PLAYERS: 8
      PVP: FALSE
      RCON_PASSWORD: ${MINESERVER_RCON_PASSWORD}
      MODRINTH_MODPACK_VERSION_TYPE: alpha
      MODRINTH_PROJECTS_VERSION_TYPE: alpha
      MODRINTH_LOADER: fabric
      MODRINTH_MODPACK: cobbleverse
      MODRINTH_PROJECTS: |
        distanthorizons
    volumes:
      - ./minecraft-data:/data
    stdin_open: true
    tty: true
  backup:
    image: itzg/mc-backup
    restart: unless-stopped
    depends_on:
      minecraft:
        condition: service_healthy
    environment:
      RCON_HOST: minecraft
      RCON_PASSWORD: ${MINESERVER_RCON_PASSWORD}
      TZ: Brazil/Sao_Paulo
      BACKUP_INTERVAL: 1h
      BACKUP_NAME: world-backup
      PRUNE_BACKUPS_DAYS: 1
      PAUSE_IF_NO_PLAYERS: TRUE
    volumes:
      - ./minecraft-data:/data:ro