services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      MEMORY: 8G
      TZ: Brazil/Sao_Paulo
      TYPE: FABRIC
      EULA: TRUE
      VERSION: 1.21.11
      MOTD: Servidor &a&l%VANILLA%&r da rapaziada na versão &b&n%VERSION%&r
      DIFFICULTY: normal
      MODE: survival
      LEVEL: world%date:yyyy-MM-dd%
      ENABLE_WHITELIST: FALSE
      WHITELIST: ""
      ONLINE_MODE: TRUE
      MAX_PLAYERS: 8
      PVP: FALSE
      MODRINTH_PROJECTS: |
        fabric-api
        lithium
        xaeros-minimap
        xaeros-world-map
        appleskin
        jei
        clumps
        c2me-fabric
        distanthorizons
        chunky
    volumes:
      - ./minecraft-data:/data
    stdin_open: true
    tty: true
  backup:
    image: itzg/mc-backup
    restart: unless-stopped
    depends_on:
      minecraft:
        condition: service_healthy
    environment:
      TZ: Brazil/Sao_Paulo
      BACKUP_INTERVAL: 30m
      BACKUP_NAME: world%date:yyyy-MM-dd%_backup
    volumes:
      - ./minecraft-data:/data:ro